name: Build and deploy .NET Core application to Web App AntDesignDocsWebApp
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: AntDesignDocsWebApp
  AZURE_WEBAPP_PACKAGE_PATH: site/AntDesign.Docs.WebApp/published
  WORKING_DIRECTORY: site/AntDesign.Docs.WebApp

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Set version number
        id: version
        run: |
          # 获取最新的 tag 作为版本号
          VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ANTBLAZOR_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version: ${VERSION}"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: |
          npm install
          dotnet build /p:Version=${VERSION} /p:AssemblyVersion=${VERSION} /p:FileVersion=${VERSION} /p:InformationalVersion=${VERSION}

      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}"

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration Release --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" /p:Version=${VERSION} /p:AssemblyVersion=${VERSION} /p:FileVersion=${VERSION} /p:InformationalVersion=${VERSION}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AntDesignDocsWebApp_6BBA }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
