# Each PR will build preview site that help to check code is work as expect.

name: Preview Build

on:
  repository_dispatch:
    types: [preview-build]

jobs:
  prepare-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: preview-build-output
          github-token: ${{ github.token }}
          run-id: ${{ github.event.client_payload.run_id }}
          path: .

      - name: Build preview site
        id: build_preview
        uses: ./.github/actions/publish
        with:
          enable-aot: true
          publish-docs: true
          publish-wasm: true
          publish-nuget: false
          publish-webapp: false
          deploy-site: false
          preview-output-path: ./wwwroot
          package-version: ${{ github.event.client_payload.package_version }}
          assembly-version: ${{ github.event.client_payload.assembly_version }}
          commit-hash: ${{ github.event.client_payload.commit_hash }}
          github-token: ${{ github.token }}

      - name: Upload preview site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./wwwroot
          retention-days: 1

  save-pr-info:
    needs: prepare-preview
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: echo ${{ github.event.client_payload.pr_number }} > ./pr-id.txt

      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
