# Each PR will build preview site that help to check code is work as expect.

name: Preview Build

on: pull_request

jobs:
  check-owner:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'
    steps:
      - run: echo "Repository owner check passed"

  build-and-publish:
    needs: check-owner
    uses: ./.github/workflows/shared-config.yml
    with:
      enable_aot: true
      run_test: false
      run_lint: false
      publish_docs: true
      publish_nuget: false
      publish_wasm: true
      publish_webapp: false

  save-pr-info:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      # Upload PR id for next workflow use
      - name: Save PR number
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
