name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - feature

jobs:
  check-owner:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'
    steps:
      - run: echo "Repository owner check passed"

  prepare:
    needs: check-owner
    uses: ./.github/workflows/shared-config.yml
    with:
      enable_aot: true
      run_test: true
      run_lint: true
      publish_docs: false
      publish_nuget: false
      publish_wasm: false
      publish_webapp: false

  upload-build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build-output

      - name: Upload build artifacts for preview
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build-output
          retention-days: 1
